version: '3.3'

services:
   api:
     image: fastdatascience/harmonyapi:20230623142723_b6cb4f2
     depends_on:
       - tika
     ports:
       - "8000:80"
     restart: always
     environment:
       DATA_PATH: /data


   tika:
     image: apache/tika:2.8.0.0-full
     ports:
       - "9998:9998"
     restart: always
