# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - wellcomeharmony

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - README.md
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - README.md
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://regprotocolsfds.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f3309a495bc843dd9498d8705fbcefe0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7271f91ab7eb4d58a18086299143cdf9 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: regprotocolsfds.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f3309a495bc843dd9498d8705fbcefe0 }}/harmony:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'wellcomeharmony'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_99ab27d3072146a9aadf2c60340e2260 }}
        images: 'regprotocolsfds.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f3309a495bc843dd9498d8705fbcefe0 }}/harmony:${{ github.sha }}'