name: "Test remote API"
# Test remote API at https://api.harmonydata.ac.uk. Github actions does not host a running API so we cannot test locally.

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.10.11]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests
      - name: Delete unwanted tests (1)
        run: tests/*local*
      - name: Delete unwanted tests (2)
        run: rm tests/*selenium*
      - name: Test with pytest
        run: |
          pip install pytest
          pytest tests